UPDATE MESA SET QRCODE = 'QRCODE01' WHERE ID = 1;
UPDATE MESA SET QRCODE = 'QRCODE02' WHERE ID = 2;
UPDATE MESA SET QRCODE = 'QRCODE03' WHERE ID = 3;
UPDATE MESA SET QRCODE = 'QRCODE04' WHERE ID = 4;
UPDATE MESA SET QRCODE = 'QRCODE05' WHERE ID = 5;

SELECT * FROM MESA;